const supportedLanguages = ["hu", "en", "de"];
const defaultLanguage = "hu";

const copy = {
  hu: {
    nav: { home: "Főoldal", about: "Rólunk", quality: "Minőség", products: "Termékek", wholesale: "Nagykereskedelem", retail: "Kiskereskedelem", grants: "Pályázatok", quote: "Ajánlatkérés", order: "Megrendelés", contact: "Kapcsolat" },
    languages: { hu: "Magyar", en: "English", de: "Deutsch" },
    buttons: { quote: "Ajánlatot kérek", order: "Megrendelést adok le", contact: "Kapcsolatfelvétel", openDetails: "Részletek megnyitása", qualityDetails: "Részletes minőségi leírás", viewWholesale: "Nagykereskedelem megtekintése", submitQuote: "Ajánlatkérés elküldése", submitOrder: "Megrendelés elküldése", goHome: "Vissza a főoldalra" },
    footer: { description: "Magyar tulajdonú, családi vállalkozásként gyorsfagyasztott gyros- és kebab termékek gyártásával, illetve országos kiszállítással állunk partnereink rendelkezésére.", legal: "Jogi oldalak", contact: "Kapcsolat", privacy: "Adatkezelési tájékoztató", complaints: "Panaszkezelési szabályzat", imprint: "Impresszum", whistleblowing: "Belső Visszaélés-Bejelentés", copyright: "© Copyright 2026 Kiskunhalasi Kebpro Kft." },
    home: { eyebrow: "Gyros- és kebab hús gyártás", title: "Minőségbiztosított húsipari gyártás Kiskunhalasról, országos lefedettséggel.", lead: "A Kiskunhalasi Kebpro Kft. gyorsfagyasztott gyros- és kebab termékeket, fűszeres húskészítményeket, valamint kiegészítő termékeket gyárt és forgalmaz partnerei számára.", advantages: "Kiemelt előnyeink", advantageItems: ["Hazai alapanyagokra épülő, ellenőrzött gyártás", "Saját hűtött gépjárműves kiszállítás", "Nyomonkövethető, stabil minőségű termékek"], qualityHeading: "Minőség és gyártás", qualityLead: "Sikerünk titka termékeink folyamatosan garantált minősége, modern technológia és a szigorú élelmiszerhigiéniai szabályok következetes betartása.", qualityCards: [{ title: "Nyersanyagok", text: "A felhasznált hús kizárólag ellenőrzött forrásból érkezik, amelyet átvételkor és feldolgozás előtt többlépcsős kontrollnak vetünk alá." }, { title: "Fagyasztás", text: "A kész termékeket elektronikus, -42°C-ra beállított hűtőkamrában sokkolásos eljárással fagyasztjuk le." }, { title: "Nyomonkövetés", text: "Minden gyártási tétel teljes körűen visszakereshető, így partnereink számára átlátható és biztonságos ellátást biztosítunk." }], logisticsEyebrow: "Logisztika", logisticsTitle: "Országos lefedettség, heti ütemezésű kiszállítással.", logisticsLead: "Saját hűtős járműveinkkel Magyarország teljes területét kiszolgáljuk. A blokk fölé vitt régiókártyákon kiemelhetők az egyes zónákhoz tartozó működési fókuszok.", logisticsPanelTitle: "Aktív logisztikai információ", logisticsPanelText: "Mozgasd az egeret a régiók fölé, és megmutatjuk az adott zónához tartozó ellátási fókuszt.", qualityPillarsTitle: "Minőségbiztosítás 5 pillére", qualityPillarsText: "A Kiskunhalasi Kebpro Kft.-nél a minőség nem külön folyamat, hanem a teljes működés alapja: ellenőrzött alapanyagok, szabályozott gyártás, sokkolásos fagyasztás, folyamatos kontroll és teljes nyomonkövethetőség.", ctaTitle: "Legyen Ön is partnerünk nagykereskedelmi vagy HORECA kiszolgálásban." },
    about: { eyebrow: "Rólunk", title: "Magyar tulajdonú, folyamatosan fejlődő élelmiszeripari gyártó cég.", introTitle: "Bemutatkozás", introText: ["A Kiskunhalasi Kebpro Kft. 2004-ben alakult, fő tevékenysége a kebab/gyros termékek gyártása és forgalmazása. 2005-től teljes mértékben magyar, családi vállalkozásként működünk, folyamatos kapacitásbővítéssel.", "Üzemünkben képzett szakemberek felügyelik a gyártás teljes folyamatát, az alapanyag-ellenőrzéstől a késztermékek csomagolásáig."], philosophyTitle: "Filozófiánk", philosophyText: ["Célunk, hogy megbízható minőségű, biztonságos és piacképes termékeket adjunk partnereinknek.", "Rendszeresen fejlesztjük technológiánkat, hogy gyorsan alkalmazkodjunk a vevői és piaci igényekhez."], logisticsTitle: "Logisztika", logisticsLead: "Saját hűtős autóinkkal az ország teljes területén végzünk kiszállítást, heti rendszerességgel, kiemelt pontokon többszöri fordulóval.", logisticsText: "A nagykereskedelmi kiszolgálásban kiemelt szerepet kap a gyors reakció, a rugalmas útvonaltervezés és a hűtőlánc folyamatos fenntartása." },
    quality: { eyebrow: "Minőség", title: "Kiemelt minőségbiztosítás a teljes gyártási és logisztikai folyamatban.", timelineTitle: "Gyártási idővonal", timelineLead: "A gyártási folyamat legfontosabb lépéseit vizuális sorrendben is kiemeltük.", sections: { quality: { title: "Kebpro minőség", paragraphs: ["Vállalatunk jelenleg mintegy 80 alkalmazottat foglalkoztat, termékeinkkel pedig az ország egész területén jelen vagyunk.", "Az élelmiszerhigiéniai szabályok maximális betartása mellett korszerű technológiai eljárásokkal és saját hűtött gépjárműveinkkel szolgáljuk ki partnereinket."] }, raw: { title: "Nyersanyagok", paragraphs: ["A termékeinkhez felhasznált húst kizárólag ellenőrzött forrásból, magyarországi partnereinktől szerezzük be.", "A nyersanyagok tekintetében napi szintű ellenőrzéseket végzünk." ] }, process: { title: "Gyártási folyamat", steps: ["A baromfihús szükség szerint megrendelésre kerül a beszállítótól.", "A leszállított áru hőmérsékletét és minőségét szakképzett kollégáink vizsgálják.", "A hús speciális hűtőházba kerül.", "A hús innen jut a gyártócsarnokba.", "A csontozást a speciális fűszerezés követi.", "Várakozási idő után a hús készen áll a döner kebab készítéséhez.", "Az ízesített csirke kebabot döner nyársra fűzzük.", "A végső súly elérése után következik a formázás és a csomagolás."] }, freezing: { title: "Fagyasztás", paragraphs: ["Az elkészült kebab nyársakat -42 °C-ra beállított speciális hűtőkamrában sokkolással lefagyasztjuk.", "Ezután -18 °C és -20 °C közötti hűtőkamrákban tároljuk őket a kiszállításig."] }, traceability: { title: "Nyomonkövetés", paragraphs: ["Az egy lépés előre, egy lépés hátra elv alapján garantáljuk az élelmiszerek biztonságát és visszakereshetőségét.", "Rendszerünk az alapanyag-beszállítótól a vevőig rögzíti a kapcsolatokat."] } } },
    services: { eyebrow: "Termékek", title: "Nagykereskedelmi termékpaletta gyros, kebab és kapcsolódó termékekhez.", introTitle: "Nagykereskedelem", introText: "A képkártyák most placeholderként működnek, így később egyszerűen csak a végleges termékfotókat kell majd a megfelelő helyre cserélni.", categoryJump: "Ugrás kategóriára", tableProduct: "Termék megnevezés", tablePack: "Kiszerelés", tableUnit: "Egység", tablePrice: "Ár", priceCustom: "Egyedi", placeholderLabel: "Termékkép helye", customText: "Bármilyen fűszerezett terméket előállítunk rendelésre, valamint friss baromfi és vízi szárnyas terméket is szállítunk. Termékeinket a HU 899-es és a HU 1439 számú saját üzemeinkben gyártjuk." },
    retail: { eyebrow: "Termékek / Kiskereskedelem", title: "Kiskereskedelmi kínálat", soon: "Hamarosan", text: "A kiskereskedelmi terméklista feltöltés alatt áll." },
    grants: { eyebrow: "Pályázatok", title: "Válassza ki, melyik pályázat részleteit szeretné megnyitni.", projectTitle: "Projekt címe", detailsEyebrow: "Pályázat részletei", beneficiary: "Kedvezményezett neve", call: "Pályázati felhívás neve, kódszáma", project: "Projekt címe, azonosító száma", amount: "Szerződött támogatás összege", supportRate: "Támogatás mértéke (%-ban)", summary: "Projekt tartalmának rövid bemutatása", endDate: "Projekt tervezett befejezési dátuma" },
    contact: { eyebrow: "Kapcsolat", title: "Vegye fel velünk a kapcsolatot.", lead: "Általános információ, partneri együttműködés vagy logisztikai kérdés esetén kollégáink készséggel állnak rendelkezésre.", details: "Elérhetőségeink", company: "Cégnév", address: "Cím", phone1: "Telefon 1", phone2: "Telefon 2", fax: "Fax", email: "E-mail", opening: "Nyitvatartás", openingHours: "H-P 08:00-16:00", quickTitle: "Gyors elérés", quickText: "Konkrét árkéréshez használja az Ajánlatkérés oldalt, megrendelés leadásához pedig a Megrendelés oldalt." },
    forms: { name: "Név", contactName: "Kapcsolattartó neve", company: "Cégnév", email: "E-mail", phone: "Telefonszám", productInterest: "Érdeklődött termék", orderedProduct: "Megrendelt termék", estimatedQuantity: "Becsült mennyiség", quantity: "Mennyiség", address: "Szállítási cím", requestedDate: "Kért szállítás dátuma", message: "Igény leírása", note: "Megjegyzés" },
    quote: { eyebrow: "Ajánlatkérés", title: "Kérjen személyre szabott ajánlatot termékeinkre.", success: "Köszönjük ajánlatkérését! Hamarosan jelentkezünk." },
    order: { eyebrow: "Megrendelés", title: "Adja le megrendelését közvetlenül online.", success: "Köszönjük megrendelését! A részletekkel hamarosan keressük." },
    errors: { notFoundTitle: "Az oldal nem található", notFoundText: "A keresett oldal nem található.", serverTitle: "Váratlan hiba", serverText: "Kérjük, próbálja meg újra később." },
  },
  en: {
    nav: { home: "Home", about: "About", quality: "Quality", products: "Products", wholesale: "Wholesale", retail: "Retail", grants: "Projects", quote: "Request Quote", order: "Order", contact: "Contact" },
    languages: { hu: "Hungarian", en: "English", de: "German" },
    buttons: { quote: "Request a quote", order: "Place an order", contact: "Get in touch", openDetails: "Open details", qualityDetails: "Detailed quality overview", viewWholesale: "View wholesale", submitQuote: "Send quote request", submitOrder: "Send order", goHome: "Back to home" },
    footer: { description: "As a Hungarian-owned family company, we supply frozen gyros and kebab products with nationwide refrigerated delivery for our partners.", legal: "Legal", contact: "Contact", privacy: "Privacy notice", complaints: "Complaint handling policy", imprint: "Imprint", whistleblowing: "Internal Whistleblowing", copyright: "© Copyright 2026 Kiskunhalasi Kebpro Ltd." },
    home: { eyebrow: "Gyros and kebab meat production", title: "Quality-assured meat production from Kiskunhalas with nationwide coverage.", lead: "Kiskunhalasi Kebpro Kft. manufactures and distributes frozen gyros and kebab products, seasoned meat products and complementary items for business partners.", advantages: "Our key advantages", advantageItems: ["Controlled production based on domestic raw materials", "In-house refrigerated fleet", "Traceable products with stable quality"], qualityHeading: "Quality and production", qualityLead: "Our success is built on consistent product quality, modern technology and strict food hygiene standards.", qualityCards: [{ title: "Raw materials", text: "All meat arrives from controlled sources and is checked at intake and again before production." }, { title: "Freezing", text: "Finished products are shock-frozen in a chamber preset to -42°C." }, { title: "Traceability", text: "Every production batch remains fully traceable for a transparent and secure supply chain." }], logisticsEyebrow: "Logistics", logisticsTitle: "Nationwide coverage with scheduled weekly deliveries.", logisticsLead: "Our own refrigerated vehicles serve the whole territory of Hungary. Hovering the region cards highlights the main operating focus of each zone.", logisticsPanelTitle: "Active logistics info", logisticsPanelText: "Move over the regions to view the key service profile for each zone.", qualityPillarsTitle: "Five pillars of quality assurance", qualityPillarsText: "At Kiskunhalasi Kebpro Kft., quality is not a separate process but the foundation of the entire operation.", ctaTitle: "Become our partner in wholesale or HORECA supply." },
    about: { eyebrow: "About", title: "Hungarian-owned food manufacturing company with continuous growth.", introTitle: "Introduction", introText: ["Kiskunhalasi Kebpro Kft. was founded in 2004. Our core activity is the production and distribution of kebab and gyros products.", "Qualified professionals supervise the full production process, from raw material control to packaging of finished goods."], philosophyTitle: "Our philosophy", philosophyText: ["Our goal is to provide partners with reliable, safe and market-ready products.", "We continuously improve our technology to respond quickly to customer and market needs."], logisticsTitle: "Logistics", logisticsLead: "With our own refrigerated vehicles we deliver across the whole country on a weekly basis, with multiple rounds in key locations.", logisticsText: "Fast reaction, flexible route planning and an uninterrupted cold chain are central to our wholesale service model." },
    quality: { eyebrow: "Quality", title: "High-level quality assurance across production and logistics.", timelineTitle: "Production timeline", timelineLead: "We also highlight the key production stages in a visual sequence.", sections: { quality: { title: "Kebpro quality", paragraphs: ["Our company currently employs around 80 people and our products are present across the whole country.", "Modern technology and our refrigerated fleet help us supply partners every day."] }, raw: { title: "Raw materials", paragraphs: ["We source the meat used in our products only from controlled suppliers in Hungary.", "Raw materials are checked daily and used in line with strict food hygiene regulations."] }, process: { title: "Production process", steps: ["Poultry meat is ordered from the supplier as needed.", "Delivered goods are checked by our qualified staff.", "The meat is moved to dedicated cold storage.", "From there it goes to the production hall.", "Deboning is followed by seasoning.", "After a resting period the meat is ready for doner production.", "The seasoned meat is assembled onto skewers.", "The final step is shaping and wrapping."] }, freezing: { title: "Freezing", paragraphs: ["Finished kebab skewers are shock-frozen in a special chamber preset to -42°C.", "They are then stored at -18°C to -20°C until delivery."] }, traceability: { title: "Traceability", paragraphs: ["Based on the principle of one step forward, one step back, we guarantee product safety and traceability.", "Our system records the connection from raw material supplier to customer."] } } },
    services: { eyebrow: "Products", title: "Wholesale product portfolio for gyros, kebab and related items.", introTitle: "Wholesale", introText: "These image cards currently act as placeholders, so later you only need to replace them with the final product photos.", categoryJump: "Jump to category", tableProduct: "Product", tablePack: "Packaging", tableUnit: "Unit", tablePrice: "Price", priceCustom: "Custom", placeholderLabel: "Product image placeholder", customText: "We manufacture seasoned products on demand and also supply fresh poultry and waterfowl products. Our products are manufactured in our own HU 899 and HU 1439 plants." },
    retail: { eyebrow: "Products / Retail", title: "Retail range", soon: "Coming soon", text: "The retail product list is currently being prepared." },
    grants: { eyebrow: "Projects", title: "Choose which project description you would like to open.", projectTitle: "Project title", detailsEyebrow: "Project details", beneficiary: "Beneficiary", call: "Call reference", project: "Project title and identifier", amount: "Contracted support amount", supportRate: "Support rate (%)", summary: "Short project description", endDate: "Planned completion date" },
    contact: { eyebrow: "Contact", title: "Get in touch with us.", lead: "For general information, partnership topics or logistics questions, our colleagues are ready to help.", details: "Contact details", company: "Company", address: "Address", phone1: "Phone 1", phone2: "Phone 2", fax: "Fax", email: "E-mail", opening: "Office hours", openingHours: "Mon-Fri 08:00-16:00", quickTitle: "Quick access", quickText: "For pricing requests please use the Request Quote page, and for direct ordering use the Order page." },
    forms: { name: "Name", contactName: "Contact person", company: "Company", email: "E-mail", phone: "Phone", productInterest: "Interested product", orderedProduct: "Ordered product", estimatedQuantity: "Estimated quantity", quantity: "Quantity", address: "Delivery address", requestedDate: "Requested delivery date", message: "Request details", note: "Note" },
    quote: { eyebrow: "Request Quote", title: "Request a tailored offer for our products.", success: "Thank you for your request. We will get back to you shortly." },
    order: { eyebrow: "Order", title: "Place your order directly online.", success: "Thank you for your order. We will contact you with the details shortly." },
    errors: { notFoundTitle: "Page not found", notFoundText: "The page you are looking for could not be found.", serverTitle: "Unexpected error", serverText: "Please try again later." },
  },
  de: {
    nav: { home: "Startseite", about: "Über uns", quality: "Qualität", products: "Produkte", wholesale: "Großhandel", retail: "Einzelhandel", grants: "Förderprojekte", quote: "Angebotsanfrage", order: "Bestellung", contact: "Kontakt" },
    languages: { hu: "Ungarisch", en: "Englisch", de: "Deutsch" },
    buttons: { quote: "Angebot anfragen", order: "Bestellung aufgeben", contact: "Kontakt", openDetails: "Details öffnen", qualityDetails: "Detaillierte Qualitätsübersicht", viewWholesale: "Großhandel ansehen", submitQuote: "Anfrage senden", submitOrder: "Bestellung senden", goHome: "Zur Startseite" },
    footer: { description: "Als ungarisches Familienunternehmen beliefern wir unsere Partner mit tiefgekühlten Gyros- und Kebabprodukten sowie gekühlter landesweiter Zustellung.", legal: "Rechtliches", contact: "Kontakt", privacy: "Datenschutzhinweis", complaints: "Beschwerdeordnung", imprint: "Impressum", whistleblowing: "Internes Hinweisgebersystem", copyright: "© Copyright 2026 Kiskunhalasi Kebpro GmbH" },
    home: { eyebrow: "Gyros- und Kebabfleischproduktion", title: "Qualitätsgesicherte Fleischproduktion aus Kiskunhalas mit landesweiter Abdeckung.", lead: "Die Kiskunhalasi Kebpro Kft. produziert und vertreibt tiefgekühlte Gyros- und Kebabprodukte, gewürzte Fleischwaren sowie ergänzende Produkte für Geschäftspartner.", advantages: "Unsere wichtigsten Vorteile", advantageItems: ["Kontrollierte Produktion auf Basis heimischer Rohstoffe", "Eigene gekühlte Fahrzeugflotte", "Rückverfolgbare Produkte mit stabiler Qualität"], qualityHeading: "Qualität und Produktion", qualityLead: "Unser Erfolg basiert auf gleichbleibender Produktqualität, moderner Technologie und strengen Lebensmittelhygienestandards.", qualityCards: [{ title: "Rohstoffe", text: "Das eingesetzte Fleisch stammt ausschließlich aus kontrollierten Quellen und wird bei der Übernahme sowie vor der Verarbeitung geprüft." }, { title: "Gefrieren", text: "Fertige Produkte werden in einer auf -42 °C eingestellten Kammer schockgefrostet." }, { title: "Rückverfolgbarkeit", text: "Jede Produktionscharge bleibt vollständig nachvollziehbar und sorgt für eine transparente und sichere Lieferkette." }], logisticsEyebrow: "Logistik", logisticsTitle: "Landesweite Abdeckung mit planmäßigen wöchentlichen Lieferungen.", logisticsLead: "Mit unseren eigenen Kühlfahrzeugen bedienen wir das gesamte Gebiet Ungarns. Beim Überfahren der Regionskarten wird der jeweilige Versorgungsschwerpunkt sichtbar.", logisticsPanelTitle: "Aktive Logistikinformation", logisticsPanelText: "Bewege die Maus über die Regionen, um das Leistungsprofil der jeweiligen Zone zu sehen.", qualityPillarsTitle: "Fünf Säulen der Qualitätssicherung", qualityPillarsText: "Bei der Kiskunhalasi Kebpro Kft. ist Qualität kein separater Prozess, sondern die Grundlage des gesamten Betriebs.", ctaTitle: "Werden Sie unser Partner im Großhandel oder in der HORECA-Belieferung." },
    about: { eyebrow: "Über uns", title: "Ungarisches Lebensmittelunternehmen mit kontinuierlicher Entwicklung.", introTitle: "Unternehmensprofil", introText: ["Die Kiskunhalasi Kebpro Kft. wurde 2004 gegründet. Unsere Haupttätigkeit ist die Herstellung und der Vertrieb von Kebab- und Gyrosprodukten.", "Qualifizierte Fachkräfte überwachen den gesamten Produktionsprozess von der Rohstoffkontrolle bis zur Verpackung der Endprodukte."], philosophyTitle: "Unsere Philosophie", philosophyText: ["Unser Ziel ist es, unseren Partnern zuverlässige, sichere und marktfähige Produkte zu liefern.", "Wir entwickeln unsere Technologie kontinuierlich weiter, um schnell auf Kunden- und Marktanforderungen reagieren zu können."], logisticsTitle: "Logistik", logisticsLead: "Mit unseren eigenen Kühlfahrzeugen beliefern wir das ganze Land wöchentlich, an wichtigen Punkten auch mit mehreren Touren.", logisticsText: "Schnelle Reaktion, flexible Routenplanung und eine durchgehende Kühlkette sind zentrale Elemente unseres Großhandelsservices." },
    quality: { eyebrow: "Qualität", title: "Hervorgehobene Qualitätssicherung im gesamten Produktions- und Logistikprozess.", timelineTitle: "Produktionszeitlinie", timelineLead: "Die wichtigsten Produktionsschritte haben wir zusätzlich visuell hervorgehoben.", sections: { quality: { title: "Kebpro-Qualität", paragraphs: ["Unser Unternehmen beschäftigt derzeit rund 80 Mitarbeitende und unsere Produkte sind landesweit präsent.", "Moderne Technologie und unsere Kühlfahrzeuge ermöglichen die tägliche Versorgung unserer Partner."] }, raw: { title: "Rohstoffe", paragraphs: ["Das verwendete Fleisch beziehen wir ausschließlich aus kontrollierten Quellen ungarischer Partner.", "Die Rohstoffe werden täglich kontrolliert und nach strengen Hygienevorschriften verarbeitet."] }, process: { title: "Produktionsprozess", steps: ["Geflügelfleisch wird je nach Bedarf bestellt.", "Die angelieferte Ware wird geprüft.", "Das Fleisch gelangt in den Kühlbereich.", "Von dort geht es in die Produktionshalle.", "Es folgen Entbeinen und Würzen.", "Nach der Ruhezeit ist das Fleisch bereit.", "Das gewürzte Fleisch wird auf Spieße gesteckt.", "Danach folgen Formgebung und Verpackung."] }, freezing: { title: "Gefrieren", paragraphs: ["Die fertigen Kebab-Spieße werden in einer auf -42 °C eingestellten Spezialkammer schockgefrostet.", "Bis zur Auslieferung lagern sie bei -18 °C bis -20 °C."] }, traceability: { title: "Rückverfolgbarkeit", paragraphs: ["Nach dem Prinzip ein Schritt vor, ein Schritt zurück gewährleisten wir die Sicherheit und Nachverfolgbarkeit der Lebensmittel.", "Unser System dokumentiert die Beziehungen vom Lieferanten bis zum Kunden."] } } },
    services: { eyebrow: "Produkte", title: "Großhandelssortiment für Gyros, Kebab und ergänzende Produkte.", introTitle: "Großhandel", introText: "Die Bildkarten funktionieren derzeit als Platzhalter, sodass später nur noch die finalen Produktfotos ersetzt werden müssen.", categoryJump: "Zur Kategorie springen", tableProduct: "Produkt", tablePack: "Verpackung", tableUnit: "Einheit", tablePrice: "Preis", priceCustom: "Individuell", placeholderLabel: "Platzhalter für Produktbild", customText: "Wir fertigen gewürzte Produkte auf Bestellung und liefern außerdem frische Geflügel- und Wassergeflügelprodukte. Unsere Produkte werden in unseren eigenen Betrieben HU 899 und HU 1439 hergestellt." },
    retail: { eyebrow: "Produkte / Einzelhandel", title: "Einzelhandelssortiment", soon: "Demnächst", text: "Die Einzelhandelsproduktliste wird derzeit vorbereitet." },
    grants: { eyebrow: "Förderprojekte", title: "Wählen Sie aus, welche Projektbeschreibung Sie öffnen möchten.", projectTitle: "Projektbezeichnung", detailsEyebrow: "Projektdetails", beneficiary: "Begünstigter", call: "Förderaufruf / Kennzeichen", project: "Projekt und Kennnummer", amount: "Vertraglich zugesagte Förderung", supportRate: "Förderquote (%)", summary: "Kurzbeschreibung des Projekts", endDate: "Geplantes Abschlussdatum" },
    contact: { eyebrow: "Kontakt", title: "Nehmen Sie Kontakt mit uns auf.", lead: "Bei allgemeinen Fragen, Partnerschaften oder logistischen Themen stehen Ihnen unsere Kolleginnen und Kollegen gerne zur Verfügung.", details: "Kontaktdaten", company: "Firma", address: "Adresse", phone1: "Telefon 1", phone2: "Telefon 2", fax: "Fax", email: "E-Mail", opening: "Öffnungszeiten", openingHours: "Mo-Fr 08:00-16:00", quickTitle: "Schnellzugriff", quickText: "Für Preisfragen nutzen Sie bitte die Seite Angebotsanfrage, für direkte Bestellungen die Seite Bestellung." },
    forms: { name: "Name", contactName: "Ansprechpartner", company: "Firma", email: "E-Mail", phone: "Telefon", productInterest: "Interessiertes Produkt", orderedProduct: "Bestelltes Produkt", estimatedQuantity: "Geschätzte Menge", quantity: "Menge", address: "Lieferadresse", requestedDate: "Gewünschtes Lieferdatum", message: "Anfragebeschreibung", note: "Bemerkung" },
    quote: { eyebrow: "Angebotsanfrage", title: "Fordern Sie ein individuelles Angebot für unsere Produkte an.", success: "Vielen Dank für Ihre Anfrage. Wir melden uns in Kürze bei Ihnen." },
    order: { eyebrow: "Bestellung", title: "Geben Sie Ihre Bestellung direkt online auf.", success: "Vielen Dank für Ihre Bestellung. Wir melden uns in Kürze mit den Details." },
    errors: { notFoundTitle: "Seite nicht gefunden", notFoundText: "Die angeforderte Seite wurde nicht gefunden.", serverTitle: "Unerwarteter Fehler", serverText: "Bitte versuchen Sie es später erneut." },
  },
};

const logisticsRegions = {
  hu: [{ key: "west", title: "Nyugat-Magyarország", text: "Stabil heti útvonalak, gyors nagykereskedelmi fordulók és rugalmas regionális kiszolgálás." }, { key: "central", title: "Közép-Magyarország", text: "Sűrű partnerháló, rövid reakcióidő és kiemelt HORECA fókusz a központi zónában." }, { key: "north", title: "Észak-Magyarország", text: "Ütemezett szállítás nagyker partnereknek, megbízható hűtőlánccal és előre tervezhető fordulókkal." }, { key: "east", title: "Kelet-Magyarország", text: "Országos kiszállítás részeként rendszeres lefedettség, egyedi igényekhez igazított logisztikai egyeztetéssel." }, { key: "south", title: "Dél-Alföld", text: "Kiskunhalasi közelségből induló, gyors újratervezést is támogató kiszolgálás." }],
  en: [{ key: "west", title: "Western Hungary", text: "Stable weekly routes, fast wholesale rounds and flexible regional coverage." }, { key: "central", title: "Central Hungary", text: "Dense partner network, short reaction times and a strong HORECA focus in the central zone." }, { key: "north", title: "Northern Hungary", text: "Scheduled deliveries for wholesale partners with reliable cold-chain handling." }, { key: "east", title: "Eastern Hungary", text: "Regular nationwide service with logistics coordination tailored to individual needs." }, { key: "south", title: "Southern Great Plain", text: "Fast-serving zone supported by proximity to Kiskunhalas and flexible replanning." }],
  de: [{ key: "west", title: "Westungarn", text: "Stabile Wochenrouten, schnelle Großhandelsfahrten und flexible regionale Versorgung." }, { key: "central", title: "Mittelungarn", text: "Dichtes Partnernetz, kurze Reaktionszeiten und starker HORECA-Fokus in der Zentralregion." }, { key: "north", title: "Nordungarn", text: "Planmäßige Auslieferung für Großhandelspartner mit verlässlicher Kühlkette." }, { key: "east", title: "Ostungarn", text: "Regelmäßige landesweite Belieferung mit auf individuelle Anforderungen abgestimmter Logistik." }, { key: "south", title: "Südliche Tiefebene", text: "Schnell bediente Zone dank der Nähe zu Kiskunhalas und flexibler Routenplanung." }],
};
const productCatalog = {
  hu: [
    { slug: "gyros-kebab", title: "Gyros/Kebab termékek", cardLead: "Gyros és kebab főtermékek, nagykereskedelmi kiszerelésekben.", items: [["Gyorsfagyasztott csirke kebab", "5,10,15,20,25,....", "kg"], ["Gyorsfagyasztott borjúhúsos kebab (EU)", "7kg, 10kg, 15kg, 20kg", "kg"], ["Gyorsfagyasztott csirke kebab csík (bőr nélkül)", "5x2kg, 10kg/karton", "kg"], ["Gyorsfagyasztott csirke sült kebab", "6x1,5kg, 9kg/karton", "kg"]] },
    { slug: "fuszeres", title: "Fűszeres termékek", cardLead: "Magyaros fűszerezésű készítmények, stabil ízprofilra optimalizálva.", items: [["Gyorsfagyasztott saslik (magyaros fűszerezésű)", "5kg/karton", "kg"], ["Gyorsfagyasztott saslik szalonnával (magyaros fűszerezésű)", "5kg/karton", "kg"]] },
    { slug: "egyeb", title: "Egyéb termékek", cardLead: "Speciális, rendeléshez igazított húskészítmények és kiegészítők.", items: [["Gyorsfagyasztott kakas taréj", "10x0,5kg, 5kg/karton", "kg"], ["Gyorsfagyasztott kakas here", "-", "kg"]] },
    { slug: "kiegeszitok", title: "Kiegészítő termékek", cardLead: "Pita, tortilla, desszert és ital kiegészítők egy helyen.", items: [["Gyorsfagyasztott (Zsebes) Pita", "70/80/90/100 gr", "db"], ["Dürüm Tortilla 25cm", "18db/zacskó", "db"], ["Dürüm Tortilla 30cm", "18db/zacskó", "db"], ["Baklava", "24db/karton", "db"], ["Marlenka Diós", "-", "db"], ["Marlenka Csokis", "-", "db"], ["Ayran Joghurt", "20db/karton", "db"]] },
    { slug: "gorog", title: "Görög termékek", cardLead: "Importált vagy kapcsolódó görög termékek a teljes kínálat kiegészítésére.", items: [["Eredeti Görög Joghurt", "5kg/egység", "egység"], ["Eredeti Görög Pita", "10db/csomag", "csomag"]] },
    { slug: "torok", title: "Török termékek", cardLead: "Kiegészítő török termékek és csomagolóanyagok partnereink részére.", items: [["Török joghurt Haydi 3,5%", "10 kg", "db"], ["Gyros zacskó nylon", "1000db/csomag", "csomag"], ["Gyros zacskó papír", "2500db/csomag", "csomag"]] },
  ],
  en: [
    { slug: "gyros-kebab", title: "Gyros/Kebab products", cardLead: "Core gyros and kebab products in wholesale packaging sizes.", items: [["Frozen chicken kebab", "5,10,15,20,25,....", "kg"], ["Frozen veal kebab (EU)", "7kg, 10kg, 15kg, 20kg", "kg"], ["Frozen chicken kebab strips (skinless)", "5x2kg, 10kg/carton", "kg"], ["Frozen roasted chicken kebab", "6x1.5kg, 9kg/carton", "kg"]] },
    { slug: "seasoned", title: "Seasoned products", cardLead: "Seasoned preparations optimized for consistent flavour profiles.", items: [["Frozen shashlik (Hungarian seasoning)", "5kg/carton", "kg"], ["Frozen shashlik with bacon (Hungarian seasoning)", "5kg/carton", "kg"]] },
    { slug: "other", title: "Other products", cardLead: "Special meat preparations and custom supporting items.", items: [["Frozen rooster comb", "10x0.5kg, 5kg/carton", "kg"], ["Frozen rooster testicle", "-", "kg"]] },
    { slug: "extras", title: "Complementary products", cardLead: "Pita, tortilla, desserts and beverage complements in one place.", items: [["Frozen pocket pita", "70/80/90/100 gr", "pcs"], ["Durum tortilla 25 cm", "18 pcs/bag", "pcs"], ["Durum tortilla 30 cm", "18 pcs/bag", "pcs"], ["Baklava", "24 pcs/carton", "pcs"], ["Marlenka Walnut", "-", "pcs"], ["Marlenka Chocolate", "-", "pcs"], ["Ayran yoghurt", "20 pcs/carton", "pcs"]] },
    { slug: "greek", title: "Greek products", cardLead: "Imported or complementary Greek items for a fuller assortment.", items: [["Original Greek yoghurt", "5kg/unit", "unit"], ["Original Greek pita", "10 pcs/pack", "pack"]] },
    { slug: "turkish", title: "Turkish products", cardLead: "Additional Turkish items and packaging materials for partners.", items: [["Turkish yoghurt Haydi 3.5%", "10 kg", "pcs"], ["Gyros nylon bag", "1000 pcs/pack", "pack"], ["Gyros paper bag", "2500 pcs/pack", "pack"]] },
  ],
  de: [
    { slug: "gyros-kebab", title: "Gyros/Kebab-Produkte", cardLead: "Zentrale Gyros- und Kebabprodukte in Großhandelsverpackungen.", items: [["Tiefgekühlter Hähnchen-Kebab", "5,10,15,20,25,....", "kg"], ["Tiefgekühlter Kalbfleisch-Kebab (EU)", "7kg, 10kg, 15kg, 20kg", "kg"], ["Tiefgekühlte Hähnchen-Kebabstreifen (ohne Haut)", "5x2kg, 10kg/Karton", "kg"], ["Tiefgekühlter gebratener Hähnchen-Kebab", "6x1,5kg, 9kg/Karton", "kg"]] },
    { slug: "seasoned", title: "Gewürzte Produkte", cardLead: "Gewürzte Zubereitungen mit stabiler Geschmackscharakteristik.", items: [["Tiefgekühltes Schaschlik (ungarische Würzung)", "5kg/Karton", "kg"], ["Tiefgekühltes Schaschlik mit Speck (ungarische Würzung)", "5kg/Karton", "kg"]] },
    { slug: "other", title: "Weitere Produkte", cardLead: "Spezielle Fleischzubereitungen und ergänzende Sonderartikel.", items: [["Tiefgekühlter Hahnenkamm", "10x0,5kg, 5kg/Karton", "kg"], ["Tiefgekühlte Hahnenhoden", "-", "kg"]] },
    { slug: "extras", title: "Ergänzende Produkte", cardLead: "Pita, Tortilla, Desserts und Getränkeergänzungen an einem Ort.", items: [["Tiefgekühlte Taschenpita", "70/80/90/100 gr", "Stk"], ["Dürüm-Tortilla 25 cm", "18 Stk/Beutel", "Stk"], ["Dürüm-Tortilla 30 cm", "18 Stk/Beutel", "Stk"], ["Baklava", "24 Stk/Karton", "Stk"], ["Marlenka Walnuss", "-", "Stk"], ["Marlenka Schoko", "-", "Stk"], ["Ayran Joghurt", "20 Stk/Karton", "Stk"]] },
    { slug: "greek", title: "Griechische Produkte", cardLead: "Importierte oder ergänzende griechische Produkte für ein vollständigeres Sortiment.", items: [["Original griechischer Joghurt", "5kg/Einheit", "Einheit"], ["Original griechische Pita", "10 Stk/Packung", "Packung"]] },
    { slug: "turkish", title: "Türkische Produkte", cardLead: "Zusätzliche türkische Produkte und Verpackungsmaterialien für unsere Partner.", items: [["Türkischer Joghurt Haydi 3,5%", "10 kg", "Stk"], ["Gyros-Beutel Nylon", "1000 Stk/Packung", "Packung"], ["Gyros-Beutel Papier", "2500 Stk/Packung", "Packung"]] },
  ],
};

const grantItems = {
  hu: [
    { slug: "vp3-4.2.1-4.2.2-2-21", title: "VP3-4.2.1-4.2.2-2-21", image: "/images/141mil.jpg", beneficiary: "KISKUNHALASI KEBPRO Élelmiszerfeldolgozó és Kereskedelmi Kft.", call: "Élelmiszeripari üzemek komplex fejlesztése; VP3-4.2.1-4.2.2-2-21", project: "A Kiskunhalasi Kebpro Kft. komplex fejlesztése; 3301640506", amount: "141.447.690 Ft", supportRate: "50%", summary: ["A projekt célja volt, hogy a termékek értéknövelését és a piacra jutást elősegítő, a technológiai fejlesztést, továbbá a környezeti erőforrás-hatékonyságot célzó komplex beruházásokat támogassa.", "A projekt végrehajtása elősegítette a Kiskunhalasi Kebpro Kft. versenyképességének javítását a legkorszerűbb, innovatív technológiák megvalósításával.", "A projekt műszaki-szakmai előrehaladása a tervezettek szerint alakult.", "Beszerzésre és beüzemelésre került többek között Fiat Ducato teherjármű, légcsere rendszer, szeletelő robot, targonca és csomagológép."], endDate: "2023.08.30." },
    { slug: "vp-3-4.2.1-15", title: "VP-3-4.2.1-15", image: "/images/159mil.jpg", beneficiary: "KISKUNHALASI KEBPRO Élelmiszer feldolgozó és Kereskedelmi Kft.", call: "Mezőgazdasági termékek értéknövelése és erőforrás-hatékonyságának elősegítése a feldolgozásban című, VP-3-4.2.1-15", project: "Mezőgazdasági termékek értéknövelése; Hússütő üzem építése a Kiskunhalasi Kebpro Kft.-nél; 1773089087", amount: "159.777.828 Ft", supportRate: "50%", summary: ["A projektben magasabb hozzáadott értékű termékek előállítása és piacbővítés érdekében új hússütő üzem létesült.", "A beruházás része volt a teljes technológia és infrastruktúra kialakítása, környezetkímélő technológiák bevezetése, megújuló energia felhasználása és új munkahelyek létrehozása.", "Kialakításra került a kapcsolódó üzemi út és járda, továbbá az alapanyag hűtéséhez és sütött termék fagyasztásához szükséges berendezések beüzemelése.", "Újdonságként bevezetésre került hővisszanyerő rendszer, megújuló energiatermelés és biológiai szennyvízkezelés."], endDate: "2018.10.31." },
  ],
  en: [
    { slug: "vp3-4.2.1-4.2.2-2-21", title: "VP3-4.2.1-4.2.2-2-21", image: "/images/141mil.jpg", beneficiary: "Kiskunhalasi Kebpro Food Processing and Trading Ltd.", call: "Complex development of food industry plants; VP3-4.2.1-4.2.2-2-21", project: "Complex development of Kiskunhalasi Kebpro Ltd.; 3301640506", amount: "HUF 141,447,690", supportRate: "50%", summary: ["The project supported complex investments improving product added value, market access, technology and resource efficiency.", "Implementation strengthened competitiveness through modern and innovative technologies.", "Technical and professional progress developed according to plan.", "Purchased assets included cargo vehicles, an air exchange system, slicing robots, a forklift and a packaging machine."], endDate: "30.08.2023" },
    { slug: "vp-3-4.2.1-15", title: "VP-3-4.2.1-15", image: "/images/159mil.jpg", beneficiary: "Kiskunhalasi Kebpro Food Processing and Trading Ltd.", call: "Improving value added and resource efficiency of agricultural products in processing; VP-3-4.2.1-15", project: "Value enhancement of agricultural products; construction of a meat roasting plant at Kiskunhalasi Kebpro Ltd.; 1773089087", amount: "HUF 159,777,828", supportRate: "50%", summary: ["A new roasting plant was created to support higher added value products and market expansion.", "The investment included full technology and infrastructure, environmentally friendly solutions, renewable energy and new jobs.", "The related service road and the required cooling and freezing equipment were also completed.", "New technologies included heat recovery, renewable energy generation and biological wastewater treatment."], endDate: "31.10.2018" },
  ],
  de: [
    { slug: "vp3-4.2.1-4.2.2-2-21", title: "VP3-4.2.1-4.2.2-2-21", image: "/images/141mil.jpg", beneficiary: "Kiskunhalasi Kebpro Lebensmittelverarbeitung und Handels GmbH", call: "Komplexe Entwicklung von lebensmittelverarbeitenden Betrieben; VP3-4.2.1-4.2.2-2-21", project: "Komplexe Entwicklung der Kiskunhalasi Kebpro GmbH; 3301640506", amount: "141.447.690 HUF", supportRate: "50%", summary: ["Das Projekt unterstützte komplexe Investitionen zur Steigerung von Produktwert, Marktzugang, Technologie und Ressourceneffizienz.", "Die Umsetzung stärkte die Wettbewerbsfähigkeit durch moderne und innovative Technologien.", "Der technische und fachliche Fortschritt verlief planmäßig.", "Beschafft wurden unter anderem Transportfahrzeuge, Luftaustauschsystem, Schneidroboter, Stapler und Verpackungsmaschine."], endDate: "30.08.2023" },
    { slug: "vp-3-4.2.1-15", title: "VP-3-4.2.1-15", image: "/images/159mil.jpg", beneficiary: "Kiskunhalasi Kebpro Lebensmittelverarbeitung und Handels GmbH", call: "Förderung der Wertsteigerung und Ressourceneffizienz landwirtschaftlicher Produkte in der Verarbeitung; VP-3-4.2.1-15", project: "Wertsteigerung landwirtschaftlicher Produkte; Bau eines Fleischbratbetriebs bei der Kiskunhalasi Kebpro GmbH; 1773089087", amount: "159.777.828 HUF", supportRate: "50%", summary: ["Ein neuer Bratbetrieb wurde errichtet, um höherwertige Produkte und Markterweiterung zu unterstützen.", "Die Investition umfasste Technologie, Infrastruktur, umweltfreundliche Verfahren, erneuerbare Energie und neue Arbeitsplätze.", "Auch Betriebsweg sowie Kühl- und Gefriertechnik wurden realisiert.", "Zu den neuen Technologien zählen Wärmerückgewinnung, erneuerbare Energie und biologische Abwasserbehandlung."], endDate: "31.10.2018" },
  ],
};

function getLang(value) { return supportedLanguages.includes(value) ? value : defaultLanguage; }
function getTranslations(lang) { return copy[getLang(lang)]; }
function getWholesaleCatalog(lang) { return productCatalog[getLang(lang)]; }
function getGrantItems(lang) { return grantItems[getLang(lang)]; }
function getLogisticsRegions(lang) { return logisticsRegions[getLang(lang)]; }
function buildLangUrl(pathname, lang, extraQuery = {}) {
  const params = new URLSearchParams();
  const currentLang = getLang(lang);
  if (currentLang !== defaultLanguage) params.set("lang", currentLang);
  Object.entries(extraQuery).forEach(([key, value]) => {
    if (value === undefined || value === null || value === "") return;
    params.set(key, value);
  });
  const queryString = params.toString();
  return queryString ? `${pathname}?${queryString}` : pathname;
}

module.exports = { supportedLanguages, defaultLanguage, getLang, getTranslations, getWholesaleCatalog, getGrantItems, getLogisticsRegions, buildLangUrl };

